name: "Prod Terraform Workflow"

#on:
 # pull_request:
  #  branches:
   #   - main
  #push:
   # branches:
    #  - main 
on:
  workflow_dispatch

permissions:
  id-token: write
  contents: read
  
jobs: 
  terraform-init-plan:
    runs-on: self-hosted
    steps: 
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 33455864-0fc4-4125-99cb-792f00370585
          tenant-id: 7c657ef7-5d58-4fff-9154-29b1e68b8b30
          subscription-id: fdab0b83-a7b6-42e6-9227-9e2fc4f971cd
            
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: environments/prod
        
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: environments/prod

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: environments/prod        
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: environments/prod    
        
  terraform-apply:    
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    needs: terraform-init-plan
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 33455864-0fc4-4125-99cb-792f00370585
          tenant-id: 7c657ef7-5d58-4fff-9154-29b1e68b8b30
          subscription-id: fdab0b83-a7b6-42e6-9227-9e2fc4f971cd
          
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: environments/prod

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        continue-on-error: true
        working-directory: environments/prod              
          
